// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/amazon-bedrock-mantle.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const AMAZON_BEDROCK_MANTLE_MODELS: ModelCatalog<typeof values, "amazon-bedrock-mantle"> =
	flattenModelCatalog("amazon-bedrock-mantle", values);
